[pytest]
base_url = https://www.saucedemo.com/

pythonpath = .

markers = 
    api: API tests no broweser
    ui: UI tests with browser

addopts = 
    --browser=chromium 
    --headed 
    ; --slowmo=1500
    ; --tracing=retain-on-failure
    --screenshot=on
    --html=report.html
    --self-contained-html
    ; --video=retain-on-failure
    --strict-markers